-- Nzela Jobs — marché de l'emploi à double sens
-- À exécuter après les migrations Supabase déjà présentes.

create extension if not exists "pgcrypto";

create table if not exists public.locations (
  id bigint generated by default as identity primary key,
  country text not null default 'République du Congo',
  city text not null,
  arrondissement text,
  name text not null,
  slug text not null unique,
  active boolean not null default true,
  source_label text,
  created_at timestamptz not null default now()
);

insert into public.locations (city, arrondissement, name, slug, source_label)
values
  ('Brazzaville', 'Makélékélé', 'Makélékélé', 'brazzaville-makelekele', 'Référentiel Nzela'),
  ('Brazzaville', 'Makélékélé', 'Kinsoundi', 'brazzaville-kinsoundi', 'Référentiel Nzela'),
  ('Brazzaville', 'Makélékélé', 'Diata', 'brazzaville-diata', 'Référentiel Nzela'),
  ('Brazzaville', 'Makélékélé', 'La Glacière', 'brazzaville-la-glaciere', 'Référentiel Nzela'),
  ('Brazzaville', 'Makélékélé', 'Météo', 'brazzaville-meteo', 'Référentiel Nzela'),
  ('Brazzaville', 'Makélékélé', 'Moukoundzi-Ngouaka', 'brazzaville-moukoundzi-ngouaka', 'Référentiel Nzela'),
  ('Brazzaville', 'Makélékélé', 'Ngangouoni', 'brazzaville-ngangouoni', 'Référentiel Nzela'),
  ('Brazzaville', 'Makélékélé', 'Mayanga', 'brazzaville-mayanga', 'Référentiel Nzela'),
  ('Brazzaville', 'Makélékélé', 'Mantsimou', 'brazzaville-mantsimou', 'Référentiel Nzela'),
  ('Brazzaville', 'Makélékélé', 'Kimbanguiste', 'brazzaville-kimbanguiste', 'Référentiel Nzela'),

  ('Brazzaville', 'Bacongo', 'Bacongo', 'brazzaville-bacongo', 'Référentiel Nzela'),
  ('Brazzaville', 'Bacongo', 'Bacongo Moderne', 'brazzaville-bacongo-moderne', 'Référentiel Nzela'),
  ('Brazzaville', 'Bacongo', 'Dahomey', 'brazzaville-dahomey', 'Référentiel Nzela'),
  ('Brazzaville', 'Bacongo', 'Mpissa', 'brazzaville-mpissa', 'Référentiel Nzela'),
  ('Brazzaville', 'Bacongo', 'Total', 'brazzaville-total', 'Référentiel Nzela'),
  ('Brazzaville', 'Bacongo', 'Case de Gaulle', 'brazzaville-case-de-gaulle', 'Référentiel Nzela'),
  ('Brazzaville', 'Bacongo', 'Saint-Pierre-Claver', 'brazzaville-saint-pierre-claver', 'Référentiel Nzela'),

  ('Brazzaville', 'Poto-Poto', 'Poto-Poto', 'brazzaville-poto-poto', 'Référentiel Nzela'),
  ('Brazzaville', 'Poto-Poto', 'Centre-ville', 'brazzaville-centre-ville', 'Référentiel Nzela'),
  ('Brazzaville', 'Poto-Poto', 'Plateau Ville', 'brazzaville-plateau-ville', 'Référentiel Nzela'),
  ('Brazzaville', 'Poto-Poto', 'Quartier Latin', 'brazzaville-quartier-latin', 'Référentiel Nzela'),
  ('Brazzaville', 'Poto-Poto', 'Sainte-Anne', 'brazzaville-sainte-anne', 'Référentiel Nzela'),
  ('Brazzaville', 'Poto-Poto', 'Marché Poto-Poto', 'brazzaville-marche-poto-poto', 'Référentiel Nzela'),

  ('Brazzaville', 'Moungali', 'Moungali', 'brazzaville-moungali', 'Référentiel Nzela'),
  ('Brazzaville', 'Moungali', 'Marché Moungali', 'brazzaville-marche-moungali', 'Référentiel Nzela'),
  ('Brazzaville', 'Moungali', 'Plateau des 15 ans', 'brazzaville-plateau-des-15-ans', 'Référentiel Nzela'),
  ('Brazzaville', 'Moungali', 'OCH', 'brazzaville-och', 'Référentiel Nzela'),
  ('Brazzaville', 'Moungali', 'Batignolles', 'brazzaville-batignolles', 'Référentiel Nzela'),
  ('Brazzaville', 'Moungali', 'Moukondo', 'brazzaville-moukondo', 'Référentiel Nzela'),
  ('Brazzaville', 'Moungali', 'Poudrière', 'brazzaville-poudriere', 'Référentiel Nzela'),
  ('Brazzaville', 'Moungali', 'Maya-Maya', 'brazzaville-maya-maya', 'Référentiel Nzela'),
  ('Brazzaville', 'Moungali', 'La Base', 'brazzaville-la-base', 'Référentiel Nzela'),

  ('Brazzaville', 'Ouenzé', 'Ouenzé', 'brazzaville-ouenze', 'Référentiel Nzela'),
  ('Brazzaville', 'Ouenzé', 'Jane-Vial', 'brazzaville-jane-vial', 'Référentiel Nzela'),
  ('Brazzaville', 'Ouenzé', 'Mouleke', 'brazzaville-mouleke', 'Référentiel Nzela'),
  ('Brazzaville', 'Ouenzé', 'Moukondo-Ouenzé', 'brazzaville-moukondo-ouenze', 'Référentiel Nzela'),
  ('Brazzaville', 'Ouenzé', 'Bouemba', 'brazzaville-bouemba', 'Référentiel Nzela'),
  ('Brazzaville', 'Ouenzé', 'Sainte-Marie', 'brazzaville-sainte-marie-ouenze', 'Référentiel Nzela'),
  ('Brazzaville', 'Ouenzé', 'Manzanza', 'brazzaville-manzanza', 'Référentiel Nzela'),
  ('Brazzaville', 'Ouenzé', 'Mpila Cent-Fils', 'brazzaville-mpila-cent-fils', 'Référentiel Nzela'),
  ('Brazzaville', 'Ouenzé', 'Kimbangou-Mikalou', 'brazzaville-kimbangou-mikalou', 'Référentiel Nzela'),

  ('Brazzaville', 'Talangaï', 'Talangaï', 'brazzaville-talangai', 'Référentiel Nzela'),
  ('Brazzaville', 'Talangaï', 'Mpila', 'brazzaville-mpila', 'Référentiel Nzela'),
  ('Brazzaville', 'Talangaï', 'Intendance', 'brazzaville-intendance', 'Référentiel Nzela'),
  ('Brazzaville', 'Talangaï', 'Texaco-Tsiémé', 'brazzaville-texaco-tsieme', 'Référentiel Nzela'),
  ('Brazzaville', 'Talangaï', 'Fleuve Congo', 'brazzaville-fleuve-congo', 'Référentiel Nzela'),
  ('Brazzaville', 'Talangaï', 'Joseph Ngobala', 'brazzaville-joseph-ngobala', 'Référentiel Nzela'),
  ('Brazzaville', 'Talangaï', 'Champ-de-Tir', 'brazzaville-champ-de-tir', 'Référentiel Nzela'),
  ('Brazzaville', 'Talangaï', 'Gaston-Lenda', 'brazzaville-gaston-lenda', 'Référentiel Nzela'),
  ('Brazzaville', 'Talangaï', 'Simba-Pelle', 'brazzaville-simba-pelle', 'Référentiel Nzela'),
  ('Brazzaville', 'Talangaï', 'Volonté Populaire', 'brazzaville-volonte-populaire', 'Référentiel Nzela'),
  ('Brazzaville', 'Talangaï', 'Maman-Mboualé', 'brazzaville-maman-mbouale', 'Référentiel Nzela'),
  ('Brazzaville', 'Talangaï', 'Ngamakosso', 'brazzaville-ngamakosso', 'Référentiel Nzela'),
  ('Brazzaville', 'Talangaï', 'Manianga', 'brazzaville-manianga', 'Référentiel Nzela'),
  ('Brazzaville', 'Talangaï', 'Mikalou', 'brazzaville-mikalou', 'Référentiel Nzela'),
  ('Brazzaville', 'Talangaï', 'Yoro', 'brazzaville-yoro', 'Référentiel Nzela'),

  ('Brazzaville', 'Mfilou', 'Mfilou', 'brazzaville-mfilou', 'Référentiel Nzela'),
  ('Brazzaville', 'Mfilou', 'Ngamaba', 'brazzaville-ngamaba', 'Référentiel Nzela'),
  ('Brazzaville', 'Mfilou', 'Nzoko-Mbimi', 'brazzaville-nzoko-mbimi', 'Référentiel Nzela'),
  ('Brazzaville', 'Mfilou', 'Massina', 'brazzaville-massina', 'Référentiel Nzela'),
  ('Brazzaville', 'Mfilou', 'Mpiéré-Mpiéré', 'brazzaville-mpiere-mpiere', 'Référentiel Nzela'),
  ('Brazzaville', 'Mfilou', 'Kibouendé', 'brazzaville-kibouende', 'Référentiel Nzela'),
  ('Brazzaville', 'Mfilou', 'Indzouli', 'brazzaville-indzouli', 'Référentiel Nzela'),
  ('Brazzaville', 'Mfilou', 'Kahounga', 'brazzaville-kahounga', 'Référentiel Nzela'),
  ('Brazzaville', 'Mfilou', 'Moutabala', 'brazzaville-moutabala', 'Référentiel Nzela'),
  ('Brazzaville', 'Mfilou', 'Cité des 17', 'brazzaville-cite-des-17', 'Référentiel Nzela'),
  ('Brazzaville', 'Mfilou', 'Mbouala', 'brazzaville-mbouala', 'Référentiel Nzela'),
  ('Brazzaville', 'Mfilou', 'Ngambio', 'brazzaville-ngambio', 'Référentiel Nzela'),
  ('Brazzaville', 'Mfilou', 'Diboulou', 'brazzaville-diboulou', 'Référentiel Nzela'),
  ('Brazzaville', 'Mfilou', 'Mitoko', 'brazzaville-mitoko', 'Référentiel Nzela'),

  ('Brazzaville', 'Madibou', 'Madibou', 'brazzaville-madibou', 'Référentiel Nzela'),
  ('Brazzaville', 'Madibou', 'Poto-Poto du Djoué', 'brazzaville-poto-poto-du-djoue', 'Référentiel Nzela'),
  ('Brazzaville', 'Madibou', 'Kibina', 'brazzaville-kibina', 'Référentiel Nzela'),
  ('Brazzaville', 'Madibou', 'Moussosso', 'brazzaville-moussosso', 'Référentiel Nzela'),
  ('Brazzaville', 'Madibou', 'Ntsangamani', 'brazzaville-ntsangamani', 'Référentiel Nzela'),
  ('Brazzaville', 'Madibou', 'Kombé', 'brazzaville-kombe', 'Référentiel Nzela'),
  ('Brazzaville', 'Madibou', 'Mbouono', 'brazzaville-mbouono', 'Référentiel Nzela'),
  ('Brazzaville', 'Madibou', 'Massissia', 'brazzaville-massissia', 'Référentiel Nzela'),
  ('Brazzaville', 'Madibou', 'Mafouta', 'brazzaville-mafouta', 'Référentiel Nzela'),
  ('Brazzaville', 'Madibou', 'Mayanga-Madibou', 'brazzaville-mayanga-madibou', 'Référentiel Nzela'),
  ('Brazzaville', 'Madibou', 'Mantsimou-Madibou', 'brazzaville-mantsimou-madibou', 'Référentiel Nzela'),
  ('Brazzaville', 'Madibou', 'Loua', 'brazzaville-loua', 'Référentiel Nzela'),

  ('Brazzaville', 'Djiri', 'Djiri', 'brazzaville-djiri', 'Référentiel Nzela'),
  ('Brazzaville', 'Djiri', 'Itsali', 'brazzaville-itsali', 'Référentiel Nzela'),
  ('Brazzaville', 'Djiri', 'Mikalou-Madzouna', 'brazzaville-mikalou-madzouna', 'Référentiel Nzela'),
  ('Brazzaville', 'Djiri', 'Matari', 'brazzaville-matari', 'Référentiel Nzela'),
  ('Brazzaville', 'Djiri', 'Nkombo', 'brazzaville-nkombo', 'Référentiel Nzela'),
  ('Brazzaville', 'Djiri', 'Jacques-Opangault', 'brazzaville-jacques-opangault', 'Référentiel Nzela'),
  ('Brazzaville', 'Djiri', 'Impôh-Manianga', 'brazzaville-impoh-manianga', 'Référentiel Nzela'),
  ('Brazzaville', 'Djiri', 'Makabandilou', 'brazzaville-makabandilou', 'Référentiel Nzela'),
  ('Brazzaville', 'Djiri', 'Massengo', 'brazzaville-massengo', 'Référentiel Nzela')
on conflict (slug) do update set
  city = excluded.city,
  arrondissement = excluded.arrondissement,
  name = excluded.name,
  active = true,
  source_label = excluded.source_label;

alter table public.profiles
  add column if not exists location_id bigint references public.locations(id) on delete set null,
  add column if not exists other_quarter_name text,
  add column if not exists profile_completed boolean not null default false,
  add column if not exists profile_completed_at timestamptz;

alter table public.jobs
  add column if not exists location_id bigint references public.locations(id) on delete set null,
  add column if not exists skills text[] not null default '{}',
  add column if not exists experience_min_years integer,
  add column if not exists education_level text,
  add column if not exists availability_required text;

create table if not exists public.candidate_profiles (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  professional_title text,
  education_level text,
  experience_years integer not null default 0 check (experience_years >= 0 and experience_years <= 60),
  biography text,
  skills text[] not null default '{}',
  preferred_contracts text[] not null default '{}',
  mobility text,
  availability text,
  salary_min numeric,
  salary_max numeric,
  cv_path text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.job_seeker_posts (
  id uuid primary key default gen_random_uuid(),
  candidate_id uuid not null references public.profiles(id) on delete cascade,
  desired_job_title text not null,
  sector text,
  description text not null,
  city text not null default 'Brazzaville',
  location_id bigint references public.locations(id) on delete set null,
  other_quarter_name text,
  contract_types text[] not null default '{}',
  skills text[] not null default '{}',
  experience_years integer not null default 0 check (experience_years >= 0 and experience_years <= 60),
  education_level text,
  availability text,
  mobility text,
  salary_min numeric,
  salary_max numeric,
  contact_visibility text not null default 'request' check (contact_visibility in ('request', 'direct')),
  status text not null default 'active' check (status in ('draft', 'active', 'expired', 'archived', 'hired', 'suspended')),
  published_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '30 days'),
  archived_at timestamptz,
  hired_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (salary_min is null or salary_max is null or salary_max >= salary_min)
);

create unique index if not exists job_seeker_posts_one_active_per_candidate
  on public.job_seeker_posts(candidate_id)
  where status = 'active';

create index if not exists job_seeker_posts_active_search_idx
  on public.job_seeker_posts(status, expires_at, city, location_id, published_at desc);

create index if not exists job_seeker_posts_candidate_idx
  on public.job_seeker_posts(candidate_id, published_at desc);

create table if not exists public.recruiter_verifications (
  id uuid primary key default gen_random_uuid(),
  recruiter_id uuid not null references public.profiles(id) on delete cascade,
  company_id uuid references public.companies(id) on delete cascade,
  professional_email text,
  document_path text,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected', 'suspended')),
  submitted_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by uuid references public.profiles(id) on delete set null,
  review_note text,
  unique(recruiter_id, company_id)
);

create table if not exists public.job_matches (
  job_id uuid not null references public.jobs(id) on delete cascade,
  job_seeker_post_id uuid not null references public.job_seeker_posts(id) on delete cascade,
  candidate_id uuid not null references public.profiles(id) on delete cascade,
  score numeric(5,2) not null default 0,
  title_score numeric(5,2) not null default 0,
  skills_score numeric(5,2) not null default 0,
  experience_score numeric(5,2) not null default 0,
  location_score numeric(5,2) not null default 0,
  contract_score numeric(5,2) not null default 0,
  availability_score numeric(5,2) not null default 0,
  education_score numeric(5,2) not null default 0,
  generated_at timestamptz not null default now(),
  primary key (job_id, job_seeker_post_id)
);

create index if not exists job_matches_rank_idx on public.job_matches(job_id, score desc);

create table if not exists public.talent_invitations (
  id uuid primary key default gen_random_uuid(),
  recruiter_id uuid not null references public.profiles(id) on delete cascade,
  company_id uuid not null references public.companies(id) on delete cascade,
  job_id uuid not null references public.jobs(id) on delete cascade,
  job_seeker_post_id uuid not null references public.job_seeker_posts(id) on delete cascade,
  candidate_id uuid not null references public.profiles(id) on delete cascade,
  message text,
  status text not null default 'sent' check (status in ('sent', 'viewed', 'accepted', 'declined', 'cancelled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(job_id, candidate_id)
);

create or replace function public.is_nzela_admin(p_user_id uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles p
    where p.id = p_user_id
      and (p.role = 'admin' or lower(p.email) = 'eliebakala@gmail.com')
  );
$$;

create or replace function public.is_verified_recruiter(p_user_id uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.is_nzela_admin(p_user_id)
    or exists (
      select 1
      from public.companies c
      where c.owner_id = p_user_id and c.verified = true
    )
    or exists (
      select 1
      from public.recruiter_verifications rv
      where rv.recruiter_id = p_user_id and rv.status = 'approved'
    );
$$;

create or replace function public.set_profile_completion_state()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.profile_completed := (
    coalesce(nullif(trim(new.phone), ''), '') <> ''
    and coalesce(nullif(trim(new.city), ''), '') <> ''
    and (new.location_id is not null or coalesce(nullif(trim(new.other_quarter_name), ''), '') <> '')
  );
  if new.profile_completed and new.profile_completed_at is null then
    new.profile_completed_at := now();
  elsif not new.profile_completed then
    new.profile_completed_at := null;
  end if;
  return new;
end;
$$;

drop trigger if exists profiles_completion_state on public.profiles;
create trigger profiles_completion_state
before insert or update of phone, city, location_id, other_quarter_name
on public.profiles
for each row execute function public.set_profile_completion_state();

create or replace function public.complete_nzela_profile(
  p_phone text,
  p_city text,
  p_location_id bigint,
  p_other_quarter_name text,
  p_role text
)
returns public.profiles
language plpgsql
security definer
set search_path = public
as $$
declare
  v_profile public.profiles;
begin
  if auth.uid() is null then
    raise exception 'AUTH_REQUIRED';
  end if;
  if coalesce(trim(p_phone), '') = '' then
    raise exception 'PHONE_REQUIRED';
  end if;
  if coalesce(trim(p_city), '') = '' then
    raise exception 'CITY_REQUIRED';
  end if;
  if p_location_id is null and coalesce(trim(p_other_quarter_name), '') = '' then
    raise exception 'QUARTER_REQUIRED';
  end if;
  if p_role not in ('candidat', 'recruteur') then
    raise exception 'INVALID_ROLE';
  end if;

  update public.profiles
  set phone = trim(p_phone),
      city = trim(p_city),
      location_id = p_location_id,
      other_quarter_name = nullif(trim(p_other_quarter_name), ''),
      role = case when role = 'admin' then role else p_role end,
      updated_at = now()
  where id = auth.uid()
  returning * into v_profile;

  return v_profile;
end;
$$;

create or replace function public.enforce_job_seeker_post_frequency()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.status = 'active' then
    if exists (
      select 1
      from public.job_seeker_posts p
      where p.candidate_id = new.candidate_id
        and p.id <> coalesce(new.id, gen_random_uuid())
        and p.published_at > now() - interval '30 days'
    ) then
      raise exception 'ONE_POST_EVERY_30_DAYS';
    end if;
    new.published_at := coalesce(new.published_at, now());
    new.expires_at := new.published_at + interval '30 days';
  end if;
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists job_seeker_posts_frequency on public.job_seeker_posts;
create trigger job_seeker_posts_frequency
before insert on public.job_seeker_posts
for each row execute function public.enforce_job_seeker_post_frequency();

create or replace function public.expire_job_seeker_posts()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_count integer;
begin
  update public.job_seeker_posts
  set status = 'expired', archived_at = coalesce(archived_at, now()), updated_at = now()
  where status = 'active' and expires_at <= now();
  get diagnostics v_count = row_count;

  delete from public.job_matches jm
  using public.job_seeker_posts p
  where p.id = jm.job_seeker_post_id
    and (p.status <> 'active' or p.expires_at <= now());

  return v_count;
end;
$$;

create or replace function public.publish_job_seeker_post(
  p_desired_job_title text,
  p_sector text,
  p_description text,
  p_city text,
  p_location_id bigint,
  p_other_quarter_name text,
  p_contract_types text[],
  p_skills text[],
  p_experience_years integer,
  p_education_level text,
  p_availability text,
  p_mobility text,
  p_salary_min numeric,
  p_salary_max numeric,
  p_contact_visibility text default 'request'
)
returns public.job_seeker_posts
language plpgsql
security definer
set search_path = public
as $$
declare
  v_profile public.profiles;
  v_post public.job_seeker_posts;
begin
  perform public.expire_job_seeker_posts();

  select * into v_profile from public.profiles where id = auth.uid();
  if v_profile.id is null then raise exception 'AUTH_REQUIRED'; end if;
  if v_profile.role <> 'candidat' then raise exception 'CANDIDATE_ONLY'; end if;
  if not v_profile.profile_completed then raise exception 'PROFILE_INCOMPLETE'; end if;
  if coalesce(trim(p_desired_job_title), '') = '' then raise exception 'JOB_TITLE_REQUIRED'; end if;
  if coalesce(trim(p_description), '') = '' then raise exception 'DESCRIPTION_REQUIRED'; end if;
  if p_location_id is null and coalesce(trim(p_other_quarter_name), '') = '' then raise exception 'QUARTER_REQUIRED'; end if;

  insert into public.job_seeker_posts (
    candidate_id, desired_job_title, sector, description, city, location_id,
    other_quarter_name, contract_types, skills, experience_years, education_level,
    availability, mobility, salary_min, salary_max, contact_visibility
  ) values (
    auth.uid(), trim(p_desired_job_title), nullif(trim(p_sector), ''), trim(p_description),
    coalesce(nullif(trim(p_city), ''), v_profile.city, 'Brazzaville'), p_location_id,
    nullif(trim(p_other_quarter_name), ''), coalesce(p_contract_types, '{}'),
    coalesce(p_skills, '{}'), greatest(coalesce(p_experience_years, 0), 0),
    nullif(trim(p_education_level), ''), nullif(trim(p_availability), ''),
    nullif(trim(p_mobility), ''), p_salary_min, p_salary_max,
    case when p_contact_visibility = 'direct' then 'direct' else 'request' end
  ) returning * into v_post;

  insert into public.candidate_profiles (
    user_id, professional_title, education_level, experience_years, biography,
    skills, preferred_contracts, mobility, availability, salary_min, salary_max, updated_at
  ) values (
    auth.uid(), v_post.desired_job_title, v_post.education_level, v_post.experience_years,
    v_post.description, v_post.skills, v_post.contract_types, v_post.mobility,
    v_post.availability, v_post.salary_min, v_post.salary_max, now()
  ) on conflict (user_id) do update set
    professional_title = excluded.professional_title,
    education_level = excluded.education_level,
    experience_years = excluded.experience_years,
    biography = excluded.biography,
    skills = excluded.skills,
    preferred_contracts = excluded.preferred_contracts,
    mobility = excluded.mobility,
    availability = excluded.availability,
    salary_min = excluded.salary_min,
    salary_max = excluded.salary_max,
    updated_at = now();

  return v_post;
end;
$$;

create or replace function public.update_job_seeker_post(
  p_post_id uuid,
  p_desired_job_title text,
  p_sector text,
  p_description text,
  p_location_id bigint,
  p_other_quarter_name text,
  p_contract_types text[],
  p_skills text[],
  p_experience_years integer,
  p_education_level text,
  p_availability text,
  p_mobility text,
  p_salary_min numeric,
  p_salary_max numeric,
  p_contact_visibility text
)
returns public.job_seeker_posts
language plpgsql
security definer
set search_path = public
as $$
declare
  v_post public.job_seeker_posts;
begin
  update public.job_seeker_posts
  set desired_job_title = trim(p_desired_job_title),
      sector = nullif(trim(p_sector), ''),
      description = trim(p_description),
      location_id = p_location_id,
      other_quarter_name = nullif(trim(p_other_quarter_name), ''),
      contract_types = coalesce(p_contract_types, '{}'),
      skills = coalesce(p_skills, '{}'),
      experience_years = greatest(coalesce(p_experience_years, 0), 0),
      education_level = nullif(trim(p_education_level), ''),
      availability = nullif(trim(p_availability), ''),
      mobility = nullif(trim(p_mobility), ''),
      salary_min = p_salary_min,
      salary_max = p_salary_max,
      contact_visibility = case when p_contact_visibility = 'direct' then 'direct' else 'request' end,
      updated_at = now()
  where id = p_post_id and candidate_id = auth.uid() and status = 'active'
  returning * into v_post;

  if v_post.id is null then raise exception 'ACTIVE_POST_NOT_FOUND'; end if;
  return v_post;
end;
$$;

create or replace function public.calculate_job_match_score(p_job_id uuid, p_post_id uuid)
returns table (
  title_score numeric,
  skills_score numeric,
  experience_score numeric,
  location_score numeric,
  contract_score numeric,
  availability_score numeric,
  education_score numeric,
  total_score numeric
)
language sql
stable
security definer
set search_path = public
as $$
with j as (
  select * from public.jobs where id = p_job_id
), p as (
  select * from public.job_seeker_posts where id = p_post_id
), scored as (
  select
    case
      when lower(trim(j.title)) = lower(trim(p.desired_job_title)) then 30
      when lower(j.title) like '%' || lower(p.desired_job_title) || '%'
        or lower(p.desired_job_title) like '%' || lower(j.title) || '%' then 24
      when lower(concat_ws(' ', j.title, j.sector, j.description))
        like '%' || lower(split_part(p.desired_job_title, ' ', 1)) || '%' then 16
      else 0
    end::numeric as title_score,
    least(25, coalesce((
      select count(*) * 5
      from unnest(p.skills) candidate_skill
      where lower(concat_ws(' ', j.title, j.sector, j.description, array_to_string(j.requirements, ' '), array_to_string(j.skills, ' ')))
        like '%' || lower(candidate_skill) || '%'
    ), 0))::numeric as skills_score,
    case
      when j.experience_min_years is null then 15
      when p.experience_years >= j.experience_min_years then 15
      when j.experience_min_years = 0 then 15
      else round((p.experience_years::numeric / j.experience_min_years::numeric) * 15, 2)
    end::numeric as experience_score,
    case
      when j.location_id is not null and j.location_id = p.location_id then 10
      when lower(coalesce(j.location, '')) = lower(coalesce(p.city, '')) then 8
      when lower(coalesce(j.location, '')) like '%' || lower(coalesce(p.city, '')) || '%' then 7
      else 0
    end::numeric as location_score,
    case
      when coalesce(cardinality(p.contract_types), 0) = 0 then 5
      when exists (select 1 from unnest(p.contract_types) ct where lower(ct) = lower(j.contract_type)) then 10
      else 0
    end::numeric as contract_score,
    case
      when j.availability_required is null then 5
      when lower(coalesce(p.availability, '')) = lower(j.availability_required) then 5
      else 2
    end::numeric as availability_score,
    case
      when j.education_level is null then 5
      when lower(coalesce(p.education_level, '')) = lower(j.education_level) then 5
      else 2
    end::numeric as education_score
  from j cross join p
)
select
  title_score,
  skills_score,
  experience_score,
  location_score,
  contract_score,
  availability_score,
  education_score,
  least(100, title_score + skills_score + experience_score + location_score + contract_score + availability_score + education_score)::numeric as total_score
from scored;
$$;

create or replace function public.rebuild_job_matches(p_job_id uuid)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_count integer;
begin
  perform public.expire_job_seeker_posts();
  delete from public.job_matches where job_id = p_job_id;

  insert into public.job_matches (
    job_id, job_seeker_post_id, candidate_id, score, title_score, skills_score,
    experience_score, location_score, contract_score, availability_score,
    education_score, generated_at
  )
  select
    p_job_id, p.id, p.candidate_id, s.total_score, s.title_score, s.skills_score,
    s.experience_score, s.location_score, s.contract_score, s.availability_score,
    s.education_score, now()
  from public.job_seeker_posts p
  cross join lateral public.calculate_job_match_score(p_job_id, p.id) s
  where p.status = 'active' and p.expires_at > now()
  order by s.total_score desc, p.published_at desc
  limit 100;

  get diagnostics v_count = row_count;
  return v_count;
end;
$$;

create or replace function public.refresh_matches_after_job_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.status = 'published' then
    perform public.rebuild_job_matches(new.id);
  else
    delete from public.job_matches where job_id = new.id;
  end if;
  return new;
end;
$$;

drop trigger if exists jobs_refresh_talent_matches on public.jobs;
create trigger jobs_refresh_talent_matches
after insert or update of title, description, location, location_id, contract_type, sector, requirements, skills, experience_min_years, education_level, availability_required, status
on public.jobs
for each row execute function public.refresh_matches_after_job_change();

create or replace function public.refresh_matches_after_post_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_job record;
begin
  if tg_op = 'DELETE' then
    delete from public.job_matches where job_seeker_post_id = old.id;
    return old;
  end if;

  if new.status <> 'active' or new.expires_at <= now() then
    delete from public.job_matches where job_seeker_post_id = new.id;
    return new;
  end if;

  for v_job in select id from public.jobs where status = 'published' loop
    perform public.rebuild_job_matches(v_job.id);
  end loop;
  return new;
end;
$$;

drop trigger if exists job_seeker_posts_refresh_matches on public.job_seeker_posts;
create trigger job_seeker_posts_refresh_matches
after insert or update of desired_job_title, sector, description, city, location_id, contract_types, skills, experience_years, education_level, availability, status, expires_at or delete
on public.job_seeker_posts
for each row execute function public.refresh_matches_after_post_change();

create or replace function public.match_job_candidates(p_job_id uuid, p_limit integer default 10)
returns table (
  job_seeker_post_id uuid,
  candidate_id uuid,
  candidate_name text,
  candidate_phone text,
  desired_job_title text,
  sector text,
  description text,
  location_name text,
  arrondissement text,
  experience_years integer,
  education_level text,
  skills text[],
  contract_types text[],
  availability text,
  contact_visibility text,
  published_at timestamptz,
  expires_at timestamptz,
  score numeric,
  title_score numeric,
  skills_score numeric,
  experience_score numeric,
  location_score numeric,
  contract_score numeric,
  availability_score numeric,
  education_score numeric
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_nzela_admin(auth.uid()) and not exists (
    select 1
    from public.jobs j
    join public.companies c on c.id = j.company_id
    where j.id = p_job_id and c.owner_id = auth.uid()
      and (c.verified = true or public.is_verified_recruiter(auth.uid()))
  ) then
    raise exception 'VERIFIED_RECRUITER_REQUIRED';
  end if;

  perform public.rebuild_job_matches(p_job_id);

  return query
  select
    p.id,
    p.candidate_id,
    trim(concat_ws(' ', pr.prenom, pr.nom)),
    case when p.contact_visibility = 'direct' then pr.phone else null end,
    p.desired_job_title,
    p.sector,
    p.description,
    coalesce(l.name, p.other_quarter_name, p.city),
    l.arrondissement,
    p.experience_years,
    p.education_level,
    p.skills,
    p.contract_types,
    p.availability,
    p.contact_visibility,
    p.published_at,
    p.expires_at,
    jm.score,
    jm.title_score,
    jm.skills_score,
    jm.experience_score,
    jm.location_score,
    jm.contract_score,
    jm.availability_score,
    jm.education_score
  from public.job_matches jm
  join public.job_seeker_posts p on p.id = jm.job_seeker_post_id
  join public.profiles pr on pr.id = p.candidate_id
  left join public.locations l on l.id = p.location_id
  where jm.job_id = p_job_id and p.status = 'active' and p.expires_at > now()
  order by jm.score desc, p.published_at desc
  limit greatest(1, least(coalesce(p_limit, 10), 50));
end;
$$;

create or replace function public.search_active_talents(
  p_query text default null,
  p_location_id bigint default null,
  p_limit integer default 50,
  p_offset integer default 0
)
returns table (
  job_seeker_post_id uuid,
  candidate_id uuid,
  candidate_name text,
  desired_job_title text,
  sector text,
  description text,
  location_name text,
  arrondissement text,
  experience_years integer,
  education_level text,
  skills text[],
  contract_types text[],
  availability text,
  published_at timestamptz,
  expires_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_verified_recruiter(auth.uid()) then
    raise exception 'VERIFIED_RECRUITER_REQUIRED';
  end if;
  perform public.expire_job_seeker_posts();

  return query
  select
    p.id,
    p.candidate_id,
    trim(concat_ws(' ', pr.prenom, pr.nom)),
    p.desired_job_title,
    p.sector,
    p.description,
    coalesce(l.name, p.other_quarter_name, p.city),
    l.arrondissement,
    p.experience_years,
    p.education_level,
    p.skills,
    p.contract_types,
    p.availability,
    p.published_at,
    p.expires_at
  from public.job_seeker_posts p
  join public.profiles pr on pr.id = p.candidate_id
  left join public.locations l on l.id = p.location_id
  where p.status = 'active'
    and p.expires_at > now()
    and (p_location_id is null or p.location_id = p_location_id)
    and (
      coalesce(trim(p_query), '') = ''
      or lower(concat_ws(' ', p.desired_job_title, p.sector, p.description, array_to_string(p.skills, ' '), l.name, l.arrondissement))
        like '%' || lower(trim(p_query)) || '%'
    )
  order by p.published_at desc
  limit greatest(1, least(coalesce(p_limit, 50), 100))
  offset greatest(coalesce(p_offset, 0), 0);
end;
$$;

create or replace function public.invite_candidate_to_job(
  p_job_id uuid,
  p_job_seeker_post_id uuid,
  p_message text default null
)
returns public.talent_invitations
language plpgsql
security definer
set search_path = public
as $$
declare
  v_company public.companies;
  v_post public.job_seeker_posts;
  v_invitation public.talent_invitations;
begin
  select c.* into v_company
  from public.jobs j join public.companies c on c.id = j.company_id
  where j.id = p_job_id and c.owner_id = auth.uid();

  if v_company.id is null or not (v_company.verified or public.is_verified_recruiter(auth.uid())) then
    raise exception 'VERIFIED_RECRUITER_REQUIRED';
  end if;

  select * into v_post
  from public.job_seeker_posts
  where id = p_job_seeker_post_id and status = 'active' and expires_at > now();
  if v_post.id is null then raise exception 'ACTIVE_TALENT_NOT_FOUND'; end if;

  insert into public.talent_invitations (
    recruiter_id, company_id, job_id, job_seeker_post_id, candidate_id, message
  ) values (
    auth.uid(), v_company.id, p_job_id, v_post.id, v_post.candidate_id, nullif(trim(p_message), '')
  )
  on conflict (job_id, candidate_id) do update set
    message = excluded.message,
    status = 'sent',
    updated_at = now()
  returning * into v_invitation;

  insert into public.notifications (user_id, title, body)
  select v_post.candidate_id,
         'Une entreprise souhaite vous rencontrer',
         concat('Votre profil correspond à l’offre « ', j.title, ' ». Consultez votre espace candidat.')
  from public.jobs j where j.id = p_job_id;

  return v_invitation;
end;
$$;

create or replace function public.admin_talent_snapshot()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_result jsonb;
begin
  if not public.is_nzela_admin(auth.uid()) then raise exception 'ADMIN_REQUIRED'; end if;
  perform public.expire_job_seeker_posts();
  select jsonb_build_object(
    'profiles_completed', (select count(*) from public.profiles where profile_completed),
    'active_job_seekers', (select count(*) from public.job_seeker_posts where status = 'active' and expires_at > now()),
    'posts_published_30d', (select count(*) from public.job_seeker_posts where published_at >= now() - interval '30 days'),
    'posts_expired', (select count(*) from public.job_seeker_posts where status = 'expired'),
    'verified_recruiters', (select count(distinct owner_id) from public.companies where verified),
    'matches_generated', (select count(*) from public.job_matches),
    'invitations_sent', (select count(*) from public.talent_invitations),
    'invitations_accepted', (select count(*) from public.talent_invitations where status = 'accepted')
  ) into v_result;
  return v_result;
end;
$$;

create or replace function public.admin_talent_by_location()
returns table (
  location_id bigint,
  quartier text,
  arrondissement text,
  registered_users bigint,
  active_job_seekers bigint
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_nzela_admin(auth.uid()) then raise exception 'ADMIN_REQUIRED'; end if;
  return query
  select
    l.id,
    l.name,
    l.arrondissement,
    count(distinct p.id)::bigint,
    count(distinct jsp.candidate_id) filter (where jsp.status = 'active' and jsp.expires_at > now())::bigint
  from public.locations l
  left join public.profiles p on p.location_id = l.id
  left join public.job_seeker_posts jsp on jsp.location_id = l.id
  where l.city = 'Brazzaville' and l.active
  group by l.id, l.name, l.arrondissement
  having count(distinct p.id) > 0 or count(distinct jsp.candidate_id) > 0
  order by active_job_seekers desc, registered_users desc, l.name;
end;
$$;

create or replace function public.admin_talent_market_balance()
returns table (
  job_family text,
  active_demands bigint,
  active_offers bigint,
  demand_per_offer numeric
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_nzela_admin(auth.uid()) then raise exception 'ADMIN_REQUIRED'; end if;
  return query
  with demands as (
    select lower(trim(desired_job_title)) family, count(*)::bigint amount
    from public.job_seeker_posts
    where status = 'active' and expires_at > now()
    group by lower(trim(desired_job_title))
  ), offers as (
    select lower(trim(title)) family, count(*)::bigint amount
    from public.jobs
    where status = 'published'
    group by lower(trim(title))
  )
  select
    coalesce(d.family, o.family),
    coalesce(d.amount, 0),
    coalesce(o.amount, 0),
    case when coalesce(o.amount, 0) = 0 then null
         else round(coalesce(d.amount, 0)::numeric / o.amount::numeric, 2)
    end
  from demands d
  full join offers o on o.family = d.family
  order by coalesce(d.amount, 0) desc, coalesce(o.amount, 0) desc
  limit 100;
end;
$$;

alter table public.locations enable row level security;
alter table public.candidate_profiles enable row level security;
alter table public.job_seeker_posts enable row level security;
alter table public.recruiter_verifications enable row level security;
alter table public.job_matches enable row level security;
alter table public.talent_invitations enable row level security;

drop policy if exists "locations public read" on public.locations;
create policy "locations public read" on public.locations for select using (active = true);

drop policy if exists "candidate profile own access" on public.candidate_profiles;
create policy "candidate profile own access" on public.candidate_profiles
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "job seeker posts own access" on public.job_seeker_posts;
create policy "job seeker posts own access" on public.job_seeker_posts
  for all using (auth.uid() = candidate_id) with check (auth.uid() = candidate_id);

drop policy if exists "verified recruiters read active talent posts" on public.job_seeker_posts;
create policy "verified recruiters read active talent posts" on public.job_seeker_posts
  for select using (public.is_verified_recruiter(auth.uid()) and status = 'active' and expires_at > now());

drop policy if exists "admins access talent posts" on public.job_seeker_posts;
create policy "admins access talent posts" on public.job_seeker_posts
  for all using (public.is_nzela_admin(auth.uid())) with check (public.is_nzela_admin(auth.uid()));

drop policy if exists "recruiter verification own read" on public.recruiter_verifications;
create policy "recruiter verification own read" on public.recruiter_verifications
  for select using (auth.uid() = recruiter_id or public.is_nzela_admin(auth.uid()));

drop policy if exists "recruiter verification own submit" on public.recruiter_verifications;
create policy "recruiter verification own submit" on public.recruiter_verifications
  for insert with check (auth.uid() = recruiter_id);

drop policy if exists "admins manage recruiter verification" on public.recruiter_verifications;
create policy "admins manage recruiter verification" on public.recruiter_verifications
  for all using (public.is_nzela_admin(auth.uid())) with check (public.is_nzela_admin(auth.uid()));

drop policy if exists "job matches recruiter read" on public.job_matches;
create policy "job matches recruiter read" on public.job_matches
  for select using (
    public.is_nzela_admin(auth.uid()) or exists (
      select 1 from public.jobs j join public.companies c on c.id = j.company_id
      where j.id = job_matches.job_id and c.owner_id = auth.uid()
    )
  );

drop policy if exists "talent invitations participant read" on public.talent_invitations;
create policy "talent invitations participant read" on public.talent_invitations
  for select using (auth.uid() = recruiter_id or auth.uid() = candidate_id or public.is_nzela_admin(auth.uid()));

drop policy if exists "talent invitations recruiter insert" on public.talent_invitations;
create policy "talent invitations recruiter insert" on public.talent_invitations
  for insert with check (auth.uid() = recruiter_id and public.is_verified_recruiter(auth.uid()));

drop policy if exists "talent invitations candidate update" on public.talent_invitations;
create policy "talent invitations candidate update" on public.talent_invitations
  for update using (auth.uid() = candidate_id or auth.uid() = recruiter_id or public.is_nzela_admin(auth.uid()));

grant select on public.locations to anon, authenticated;
grant select, insert, update on public.candidate_profiles to authenticated;
grant select, insert, update on public.job_seeker_posts to authenticated;
grant select, insert on public.recruiter_verifications to authenticated;
grant select on public.job_matches to authenticated;
grant select, insert, update on public.talent_invitations to authenticated;
grant usage, select on sequence public.locations_id_seq to anon, authenticated;

grant execute on function public.complete_nzela_profile(text, text, bigint, text, text) to authenticated;
grant execute on function public.expire_job_seeker_posts() to authenticated;
grant execute on function public.publish_job_seeker_post(text, text, text, text, bigint, text, text[], text[], integer, text, text, text, numeric, numeric, text) to authenticated;
grant execute on function public.update_job_seeker_post(uuid, text, text, text, bigint, text, text[], text[], integer, text, text, text, numeric, numeric, text) to authenticated;
grant execute on function public.match_job_candidates(uuid, integer) to authenticated;
grant execute on function public.search_active_talents(text, bigint, integer, integer) to authenticated;
grant execute on function public.invite_candidate_to_job(uuid, uuid, text) to authenticated;
grant execute on function public.admin_talent_snapshot() to authenticated;
grant execute on function public.admin_talent_by_location() to authenticated;
grant execute on function public.admin_talent_market_balance() to authenticated;

revoke execute on function public.calculate_job_match_score(uuid, uuid) from anon, authenticated;
revoke execute on function public.rebuild_job_matches(uuid) from anon, authenticated;

select public.expire_job_seeker_posts();
